name: CI-version

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always
  
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toolchain:
          - stable
          - nightly
        features:
          -
          - --features u128
          - --features serde
          - --features rocket
          - --features bit
          - --features bit --features serde
          - --features bit --features rocket
          - --features u128 --features serde
          - --features u128 --features bit
          - --features u128 --features bit --features serde
          - --no-default-features
          - --no-default-features --features byte
          - --no-default-features --features byte --features serde
          - --no-default-features --features byte --features rocket
          - --no-default-features --features bit
          - --no-default-features --features bit --features serde
          - --no-default-features --features bit --features rocket
          - --no-default-features --features byte --features bit
          - --no-default-features --features u128
          - --no-default-features --features u128 --features byte
          - --no-default-features --features u128 --features byte --features serde
          - --no-default-features --features u128 --features bit
          - --no-default-features --features u128 --features bit --features serde
          - --no-default-features --features u128 --features byte --features bit
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }} (${{ matrix.features }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --release ${{ matrix.features }}
      - run: cargo doc --release ${{ matrix.features }}

  MSRV:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toolchain:
          - "1.70"
        features:
          -
          - --features u128
          - --features serde
          - --features rocket
          - --features bit
          - --features bit --features serde
          - --features bit --features rocket
          - --features u128 --features serde
          - --features u128 --features bit
          - --features u128 --features bit --features serde
          - --no-default-features
          - --no-default-features --features byte
          - --no-default-features --features byte --features serde
          - --no-default-features --features byte --features rocket
          - --no-default-features --features bit
          - --no-default-features --features bit --features serde
          - --no-default-features --features bit --features rocket
          - --no-default-features --features byte --features bit
          - --no-default-features --features u128
          - --no-default-features --features u128 --features byte
          - --no-default-features --features u128 --features byte --features serde
          - --no-default-features --features u128 --features bit
          - --no-default-features --features u128 --features bit --features serde
          - --no-default-features --features u128 --features byte --features bit
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }} (${{ matrix.features }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --release --lib --bins ${{ matrix.features }}